# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f246f4ef0a88cf0d07dd3be8f0a9a56452c75ebd7312885ec443c60ce201577595164bcf74ab8dea00b5855faedd373d4f1e5f04a0e2348f3bd2b9ca2ccf0419

test:
  secret_key_base: 3f6d35cc25f368c1cd7a112f832f6c61951a71c5ea4a5dfd99e39609c333e720a7465440166295f070d6bd4bdb5aa74bc513e8fda18cc6380e5582ec53c20a16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
